x-operator: &operator
  build: .
  image: ssv-dkg:latest
  networks:
    - shared_network
  restart: unless-stopped
  environment: &operator-env
    CA: /ssv-dkg/data/initiator/rootCA.crt
    CAkey: /ssv-dkg/data/initiator/rootCA.key
  volumes:
    - ./examples:/ssv-dkg/data
  healthcheck:
    test: ["CMD", "wget", "--no-check-certificate", "-q", "-O", "/dev/null", "https://localhost:3030/health_check"]
    interval: 5s
    timeout: 3s
    retries: 3
    start_period: 10s

services:
  ethnode:
    image: ethereum/client-go:stable
    networks:
      - shared_network
    restart: unless-stopped
    ports:
      - "8545:8545"
      - "30303:30303"
    command:
      [
        "--holesky",
        "--ipcdisable",
        "--http",
        "--http.addr",
        "0.0.0.0",
        "--http.port",
        "8545",
        "--http.vhosts=*",
      ]

  operator1:
    <<: *operator
    ports:
      - "3030:3030"
    environment:
      <<: *operator-env
      CN: operator1
    command: ["start-operator", "--configPath", "./data/config/operator1.example.yaml"]

  operator2:
    <<: *operator
    ports:
      - "3031:3030"
    environment:
      <<: *operator-env
      CN: operator2
    command: ["start-operator", "--configPath", "./data/config/operator2.example.yaml"]

  operator3:
    <<: *operator
    ports:
      - "3032:3030"
    environment:
      <<: *operator-env
      CN: operator3
    command: ["start-operator", "--configPath", "./data/config/operator3.example.yaml"]

  operator4:
    <<: *operator
    ports:
      - "3033:3030"
    environment:
      <<: *operator-env
      CN: operator4
    command: ["start-operator", "--configPath", "./data/config/operator4.example.yaml"]

  operator5:
    <<: *operator
    ports:
      - "3034:3030"
    environment:
      <<: *operator-env
      CN: operator5
    command: ["start-operator", "--configPath", "./data/config/operator5.example.yaml"]

  operator6:
    <<: *operator
    ports:
      - "3035:3030"
    environment:
      <<: *operator-env
      CN: operator6
    command: ["start-operator", "--configPath", "./data/config/operator6.example.yaml"]

  operator7:
    <<: *operator
    ports:
      - "3036:3030"
    environment:
      <<: *operator-env
      CN: operator7
    command: ["start-operator", "--configPath", "./data/config/operator7.example.yaml"]

  operator8:
    <<: *operator
    ports:
      - "3037:3030"
    environment:
      <<: *operator-env
      CN: operator8
    command: ["start-operator", "--configPath", "./data/config/operator8.example.yaml"]

  operator9:
    <<: *operator
    ports:
      - "3038:3030"
    environment:
      <<: *operator-env
      CN: operator9
    command: ["start-operator", "--configPath", "./data/config/operator9.example.yaml"]

  operator10:
    <<: *operator
    ports:
      - "3039:3030"
    environment:
      <<: *operator-env
      CN: operator10
    command: ["start-operator", "--configPath", "./data/config/operator10.example.yaml"]

  operator11:
    <<: *operator
    ports:
      - "3041:3030"
    environment:
      <<: *operator-env
      CN: operator11
    command: ["start-operator", "--configPath", "./data/config/operator11.example.yaml"]

  operator12:
    <<: *operator
    ports:
      - "3042:3030"
    environment:
      <<: *operator-env
      CN: operator12
    command: ["start-operator", "--configPath", "./data/config/operator12.example.yaml"]

  operator13:
    <<: *operator
    ports:
      - "3043:3030"
    environment:
      <<: *operator-env
      CN: operator13
    command: ["start-operator", "--configPath", "./data/config/operator13.example.yaml"]

  initiator:
    <<: *operator
    depends_on:
      operator1:
        condition: service_healthy
      operator2:
        condition: service_healthy
      operator3:
        condition: service_healthy
      operator4:
        condition: service_healthy
    command: ["init", "--configPath", "./data/config/initiator.example.yaml"]

  generate-resign-msg:
    <<: *operator
    restart: "no"
    command: ["generate-resign-msg", "--configPath", "./data/config/resign.example.yaml"]

  resign:
    <<: *operator
    depends_on:
      operator1:
        condition: service_healthy
      operator2:
        condition: service_healthy
      operator3:
        condition: service_healthy
      operator4:
        condition: service_healthy
    command: ["resign", "--configPath", "./data/config/resign.example.yaml"]

  generate-reshare-msg:
    <<: *operator
    restart: "no"
    command: ["generate-reshare-msg", "--configPath", "./data/config/reshare.example.yaml"]

  reshare:
    <<: *operator
    depends_on:
      ethnode:
        condition: service_started
      operator1:
        condition: service_healthy
      operator2:
        condition: service_healthy
      operator3:
        condition: service_healthy
      operator4:
        condition: service_healthy
      operator5:
        condition: service_healthy
      operator6:
        condition: service_healthy
      operator7:
        condition: service_healthy
      operator8:
        condition: service_healthy
    command: ["reshare", "--configPath", "./data/config/reshare.example.yaml"]

  ping:
    <<: *operator
    restart: "no"
    command:
      [
        "ping",
        "--ip",
        "https://operator9:3030,https://operator10:3030,https://operator11:3030,https://operator12:3030,https://operator13:3030",
      ]

networks:
  shared_network:
