# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main", "unstable"]
  pull_request:
    branches: ["main", "unstable"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test ./... -timeout 3600s

      - name: Critic
        run: go install -v github.com/go-critic/go-critic/cmd/gocritic@latest && gocritic check ./...

      - name: Lint
        run: make lint-prepare && make lint
